### ISSUE TITLE
Add first milestone in Github.

### ISSUE THREAD

**Issue by stas-at-ibm** [lukatarman/steam-game-stats-backend#41]
## Description
A compilation of tasks/issues/features for a _first milestone_ of the steam charts application. 

Having those tasks finished means @lukatarman can start the application process. He also has the necessary skill to proceed with the application with only little guidance and support from a senior engineer.

## Definition of Done
- [x] Backend application setup
- [x] Unit testing setup
- [x] Basic project structure w. layered architecture
   - [x] main, orchestration|controller|aggregator, service, model
   - [x] infrastructure, shared
- [x] minimal feature set
  - [x] aggregate steam apps
  - [x] identify games
  - [x] aggregate current/history player numbers
  - [x] reading of game data over REST API
  - [x] display table of games in a browser UI
